Update Job

diff --git a/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml b/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml
--- a/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml
+++ b/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml
@@ -13,8 +13,6 @@ spec:
           env:
             - name: ROX_CENTRAL_ENDPOINT
               value: {{ .Values.central.endpoint }} 
-            - name: ROX_API_TOKEN
-              value:  {{ .Values.central.token }}
             - name: ROX_BUNDLE_NAME
               value:  {{ .Values.clusterName }}
             - name: PASSWORD
@@ -27,61 +25,44 @@ spec:
             - -c
             - |
               #!/usr/bin/env bash
+              if oc get secret/sensor-tls &> /dev/null; then
+                echo "Error: cluster-init bundle has already been configured, doing nothing"
+                exit 0
+              else
               # Wait for central to be ready
               attempt_counter=0
               max_attempts=20
-              echo "Waiting for central to be available..."
+              echo "INFO: Waiting for central to be available..."
               until $(curl -k --output /dev/null --silent --head --fail https://$ROX_CENTRAL_ENDPOINT:443); do
                   if [ ${attempt_counter} -eq ${max_attempts} ];then
-                    echo "Max attempts reached"
+                    echo "INFO/ Max attempts reached"
                     exit 1
                   fi
 
                   printf '.'
                   attempt_counter=$(($attempt_counter+1))
-                  echo "Made attempt $attempt_counter, waiting..."
+                  echo "INFO: Made attempt $attempt_counter, waiting..."
                   sleep 5
               done
-              echo "INFO: The central is available ..."
 
-              curl -s -v -k -L -H "Authorization: Bearer admin:$PASSWORD" https://$ROX_CENTRAL_ENDPOINT:443/api/cli/download/roxctl-linux -o /tmp/roxctl
-              if [ $? -eq 0 ]; then
-                  echo "INFO: Retrieve of roxctl command succeed"
-              else
-                  echo "Error: Retrieve of roxctl command failed"
-                  exit 1
-              fi
+                echo "INFO: The central is available ..."
+                echo "INFO: Generating cluster-init bundle"
+                export DATA={\"name\":\"$ROX_BUNDLE_NAME\"}
+                curl -k -o /tmp/bundle.json -X POST -u "admin:$PASSWORD" -H "Content-Type: application/json" --data $DATA https://central/v1/cluster-init/init-bundles
+                if [ $? -eq 0 ]; then
+                    echo "INFO: Retrieve init bundles succeed"
+                else
+                    echo "Error: Retrieve init bundles failed"
+                    exit 1
+                fi
+                echo "Bundle received"
+                cat /tmp/bundle.json
 
-              chmod +x /tmp/roxctl
-              if [ $? -eq 0 ]; then
-                  echo "INFO: Change roxctl command rigths succeed"
-              else
-                  echo "Error: Change roxctl command rigths failed"
-                  exit 1
-              fi
-              
-              /tmp/roxctl --insecure-skip-tls-verify central init-bundles generate $ROX_BUNDLE_NAME  --endpoint $ROX_CENTRAL_ENDPOINT:443  --output-secrets /tmp/"$ROX_BUNDLE_NAME".yaml
-              if [ $? -eq 0 ]; then
-                  echo "INFO: Retrieve init bundles succeed"
-              else
-                  echo "Error: Retrieve init bundles failed"
-                  exit 1
-              fi
-
-              if oc get secret/sensor-tls &> /dev/null; then
-                echo "Error: cluster-init bundle has already been configured, doing nothing"
-                exit 0
-              else
-
-                # Display init bundle generated
-                cat /tmp/"$ROX_BUNDLE_NAME".yaml
-
-                echo "INFO: Applying init bundle generated "
+                echo "Applying bundle"
                 # No jq in container, python to the rescue
-                oc apply -f /tmp/"$ROX_BUNDLE_NAME".yaml
-
+                cat /tmp/bundle.json | python3 -c "import sys, json; print(json.load(sys.stdin)['kubectlBundle'])" | base64 -d | oc apply -f -
                 # Touch SecuredCluster to force operator to reconcile
-                oc label SecuredCluster stackrox-secured-cluster-services cluster-init-job-status=created
+                oc label SecuredCluster local-cluster cluster-init-job-status=created
 
                 echo "INFO: ACS Cluster init bundle generated and applied"
               fi
