Add exit code to control bash on Job

diff --git a/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml b/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml
--- a/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml
+++ b/rhacs/acs-secured-cluster/templates/create-cluster-init-bundle-job.yaml
@@ -22,8 +22,6 @@ spec:
             - -c
             - |
               #!/usr/bin/env bash
-              #set +x
-              export NO_COLOR="True"
               # Wait for central to be ready
               attempt_counter=0
               max_attempts=20
@@ -42,11 +40,29 @@ spec:
               echo "The central is available ..."
 
               curl -s -k -L -H "Authorization: Bearer $ROX_API_TOKEN" https://$ROX_CENTRAL_ENDPOINT:443/api/cli/download/roxctl-linux -o /tmp/roxctl
-              
-              chmod +x /tmp/roxctl
+              if [ $? -eq 0 ]; then
+                  echo "Retrieve of roxctl command succeed"
+              else
+                  echo "Retrieve of roxctl command failed"
+                  exit 1
+              fi
 
-              /tmp/roxctl --insecure-skip-tls-verify central init-bundles generate $ROX_BUNDLE_NAME  --endpoint $ROX_CENTRAL_ENDPOINT:443  --output-secrets /tmp/"$ROX_BUNDLE_NAME".yaml
+              chmod +x /tmp/roxctl
+              if [ $? -eq 0 ]; then
+                  echo "Change roxctl command rigths succeed"
+              else
+                  echo "Change roxctl command rigths failed"
+                  exit 1
+              fi
               
+              /tmp/roxctl --insecure-skip-tls-verify central init-bundles generate $ROX_BUNDLE_NAME  --endpoint $ROX_CENTRAL_ENDPOINT:443  --output-secrets /tmp/"$ROX_BUNDLE_NAME".yaml
+              if [ $? -eq 0 ]; then
+                  echo "Retrieve init bundles succeed"
+              else
+                  echo "Retrieve init bundles failed"
+                  exit 1
+              fi
+
               if oc get secret/sensor-tls &> /dev/null; then
                 echo "cluster-init bundle has already been configured, doing nothing"
                 exit 0
